/*
 * Copyright (C) 2011-2021 Intel Corporation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *   * Neither the name of Intel Corporation nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */



#include "service_provider.h"
#include "sample_libcrypto.h"
#include "ecp.h"
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <time.h>
#include <string.h>
#include "ias_ra.h"

//This whole file is used as simulation of the interfaces to be
// delivered an attestation server.


#define UNUSED(expr) do { (void)(expr); } while (0)

#if !defined(SWAP_ENDIAN_DW)
    #define SWAP_ENDIAN_DW(dw)	((((dw) & 0x000000ff) << 24)                \
    | (((dw) & 0x0000ff00) << 8)                                            \
    | (((dw) & 0x00ff0000) >> 8)                                            \
    | (((dw) & 0xff000000) >> 24))
#endif
#if !defined(SWAP_ENDIAN_32B)
    #define SWAP_ENDIAN_32B(ptr)                                            \
{\
    unsigned int temp = 0;                                                  \
    temp = SWAP_ENDIAN_DW(((unsigned int*)(ptr))[0]);                       \
    ((unsigned int*)(ptr))[0] = SWAP_ENDIAN_DW(((unsigned int*)(ptr))[7]);  \
    ((unsigned int*)(ptr))[7] = temp;                                       \
    temp = SWAP_ENDIAN_DW(((unsigned int*)(ptr))[1]);                       \
    ((unsigned int*)(ptr))[1] = SWAP_ENDIAN_DW(((unsigned int*)(ptr))[6]);  \
    ((unsigned int*)(ptr))[6] = temp;                                       \
    temp = SWAP_ENDIAN_DW(((unsigned int*)(ptr))[2]);                       \
    ((unsigned int*)(ptr))[2] = SWAP_ENDIAN_DW(((unsigned int*)(ptr))[5]);  \
    ((unsigned int*)(ptr))[5] = temp;                                       \
    temp = SWAP_ENDIAN_DW(((unsigned int*)(ptr))[3]);                       \
    ((unsigned int*)(ptr))[3] = SWAP_ENDIAN_DW(((unsigned int*)(ptr))[4]);  \
    ((unsigned int*)(ptr))[4] = temp;                                       \
}
#endif

// This is the ECDSA NIST P-256 private key used to sign platform_info_blob.
// This private
// key and the public key in SDK untrusted KElibrary should be a temporary key
// pair. For production parts an attestation server will sign the platform_info_blob with the
// production private key and the SDK untrusted KE library will have the public
// key for verification.

static const sample_ec256_private_t g_rk_priv_key =
{{
    0x63,0x2c,0xd4,0x02,0x7a,0xdc,0x56,0xa5,
    0x59,0x6c,0x44,0x3e,0x43,0xca,0x4e,0x0b,
    0x58,0xcd,0x78,0xcb,0x3c,0x7e,0xd5,0xb9,
    0xf2,0x91,0x5b,0x39,0x0d,0xb3,0xb5,0xfb
}};

static sample_spid_t g_sim_spid = {"Service X"};


// Simulates the attestation server function for verifying the quote produce by
// the ISV enclave. It doesn't decrypt or verify the quote in
// the simulation.  Just produces the attestaion verification
// report with the platform info blob.
//
// @param p_isv_quote Pointer to the quote generated by the ISV
//                    enclave.
// @param pse_manifest Pointer to the PSE manifest if used.
// @param p_attestation_verification_report Pointer the outputed
//                                          verification report.
//
// @return int

int ias_verify_attestation_evidence(
    const sample_quote_t *p_isv_quote,
    uint8_t* pse_manifest,
    ias_att_report_t* p_attestation_verification_report)
{
    int ret = 0;
    sample_ecc_state_handle_t ecc_state = NULL;

    //unused parameters
    UNUSED(pse_manifest);

    if((NULL == p_isv_quote) ||
        (NULL == p_attestation_verification_report))
    {
        return -1;
    }
    //Decrypt the Quote signature and verify.

    p_attestation_verification_report->id = 0x12345678;
    p_attestation_verification_report->status = IAS_QUOTE_OK;
    p_attestation_verification_report->revocation_reason =
        IAS_REVOC_REASON_NONE;
    p_attestation_verification_report->info_blob.sample_epid_group_status =
        0 << IAS_EPID_GROUP_STATUS_REVOKED_BIT_POS
        | 0 << IAS_EPID_GROUP_STATUS_REKEY_AVAILABLE_BIT_POS;
    p_attestation_verification_report->info_blob.sample_tcb_evaluation_status =
        0 << IAS_TCB_EVAL_STATUS_CPUSVN_OUT_OF_DATE_BIT_POS
        | 0 << IAS_TCB_EVAL_STATUS_ISVSVN_OUT_OF_DATE_BIT_POS;
    p_attestation_verification_report->info_blob.pse_evaluation_status =
        0 << IAS_PSE_EVAL_STATUS_ISVSVN_OUT_OF_DATE_BIT_POS
        | 0 << IAS_PSE_EVAL_STATUS_EPID_GROUP_REVOKED_BIT_POS
        | 0 << IAS_PSE_EVAL_STATUS_PSDASVN_OUT_OF_DATE_BIT_POS
        | 0 << IAS_PSE_EVAL_STATUS_SIGRL_OUT_OF_DATE_BIT_POS
        | 0 << IAS_PSE_EVAL_STATUS_PRIVRL_OUT_OF_DATE_BIT_POS;
    memset(p_attestation_verification_report->
                info_blob.latest_equivalent_tcb_psvn, 0, PSVN_SIZE);
    memset(p_attestation_verification_report->info_blob.latest_pse_isvsvn,
           0, ISVSVN_SIZE);
    memset(p_attestation_verification_report->info_blob.latest_psda_svn,
           0, PSDA_SVN_SIZE);
    memset(p_attestation_verification_report->info_blob.performance_rekey_gid,
           0, GID_SIZE);

    // @TODO: Product signing algorithm still TBD.  May be RSA2048 signing.
    // Generate the Service providers ECDH key pair.
    do {
        ret = sample_ecc256_open_context(&ecc_state);
        if (SAMPLE_SUCCESS != ret) {
            fprintf(stderr, "\nError, cannot get ECC cotext in [%s].",
                    __FUNCTION__);
            ret = -1;
            break;
        }
        // Sign
        ret = sample_ecdsa_sign(
                (uint8_t *)&p_attestation_verification_report->
                    info_blob.sample_epid_group_status,
                sizeof(ias_platform_info_blob_t) - sizeof(sample_ec_sign256_t),
                (sample_ec256_private_t *)&g_rk_priv_key,
                (sample_ec256_signature_t *)&p_attestation_verification_report->
                    info_blob.signature,
                ecc_state);
        if (SAMPLE_SUCCESS != ret) {
            fprintf(stderr, "\nError, sign ga_gb fail in [%s].", __FUNCTION__);
            ret = SP_INTERNAL_ERROR;
            break;
        }
        SWAP_ENDIAN_32B(p_attestation_verification_report->
                            info_blob.signature.x);
        SWAP_ENDIAN_32B(p_attestation_verification_report->
                            info_blob.signature.y);

    }while (0);
    if (ecc_state) {
        sample_ecc256_close_context(ecc_state);
    }
    p_attestation_verification_report->pse_status = IAS_PSE_OK;

    // For now, don't simulate the policy reports.
    p_attestation_verification_report->policy_report_size = 0;
    return(ret);
}


unsigned char sigrl_dat[] = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x7f, 0xff, 0xff, 0xee,
  0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x03,
  0xa6, 0xad, 0xdd, 0xbe, 0x45, 0xcc, 0x88, 0xcc,
  0x18, 0x30, 0x68, 0x49, 0x77, 0xfe, 0xc0, 0x4f,
  0xf9, 0x27, 0xa9, 0x49, 0x66, 0x03, 0x1a, 0x3c,
  0x3c, 0x4f, 0xac, 0xb6, 0x94, 0x2e, 0xd7, 0xb0,
  0x01, 0xa3, 0x8c, 0x5e, 0x73, 0x1d, 0x2f, 0x20,
  0x86, 0xb7, 0x10, 0xbd, 0x8e, 0x63, 0x5b, 0x41,
  0x21, 0x23, 0x8d, 0xac, 0x87, 0xc0, 0x7e, 0x78,
  0xb2, 0x11, 0x33, 0x52, 0x50, 0xa7, 0x6f, 0x7a,
  0x09, 0x95, 0x63, 0x1b, 0x04, 0xce, 0x6b, 0x93,
  0x47, 0xa2, 0xb0, 0x1f, 0x2c, 0x89, 0x1c, 0xd7,
  0xaa, 0xd6, 0x88, 0xbd, 0xd5, 0x45, 0x6f, 0x06,
  0x2b, 0xcc, 0x3e, 0x02, 0x4f, 0xeb, 0xef, 0x9d,
  0xb2, 0xf9, 0x71, 0xea, 0xca, 0x8c, 0x9c, 0x00,
  0xcd, 0x7e, 0x1c, 0x15, 0x7d, 0x69, 0xe8, 0x52,
  0x03, 0x81, 0xc4, 0x31, 0x2e, 0x8f, 0x0d, 0x31,
  0xef, 0x18, 0x03, 0x37, 0x0f, 0xa3, 0x19, 0x7b,
  0x19, 0x6a, 0x11, 0x7c, 0xfb, 0x88, 0xd3, 0x08,
  0x17, 0x98, 0x9d, 0xd6, 0x5a, 0x87, 0xd3, 0xe8,
  0x69, 0x3f, 0x6c, 0x8b, 0xd8, 0xd4, 0x6c, 0x11,
  0x17, 0x2b, 0xae, 0xf2, 0x8d, 0xa4, 0x35, 0x55,
  0x32, 0x9e, 0x85, 0x6a, 0xc2, 0x9e, 0xee, 0x5b,
  0xcd, 0x23, 0x7a, 0x11, 0xa7, 0xdd, 0xde, 0xb2,
  0xd1, 0xc6, 0xb8, 0x02, 0x93, 0xdb, 0x1e, 0x69,
  0x99, 0x6d, 0xc6, 0x2f, 0x98, 0xab, 0x26, 0x89,
  0x02, 0x83, 0xfa, 0xa6, 0x65, 0xe9, 0xc6, 0x9f,
  0xf7, 0xc9, 0x7b, 0xda, 0x73, 0x1c, 0x60, 0x11,
  0x32, 0x85, 0x17, 0x49, 0xca, 0x0b, 0x96, 0x0c,
  0x47, 0x0d, 0xef, 0x94, 0x9c, 0x15, 0x05, 0xbe,
  0x4b, 0xed, 0xd6, 0xee, 0x7b, 0xbb, 0x14, 0x23,
  0x54, 0x31, 0x04, 0xf0, 0x81, 0x04, 0x44, 0xd2,
  0x02, 0x33, 0x60, 0xba, 0x5f, 0x4f, 0xae, 0x1f,
  0x2d, 0xce, 0xbb, 0xff, 0xe8, 0x55, 0xc7, 0xa8,
  0xa6, 0x50, 0xbe, 0xa7, 0xfb, 0x41, 0x9d, 0xf8,
  0x41, 0x9c, 0xdd, 0x92, 0x47, 0x9f, 0x6f, 0xf3,
  0x56, 0x25, 0x0e, 0xbc, 0xa0, 0x89, 0xf2, 0x7f,
  0x12, 0x45, 0x5b, 0xb4, 0xd6, 0xa5, 0xb5, 0x71,
  0x31, 0x70, 0xae, 0xaf, 0x65, 0x55, 0x0e, 0xa9,
  0x1a, 0x5d, 0xc0, 0x1f, 0x20, 0x71, 0x07, 0xce,
  0x3e, 0x5e, 0xd3, 0xee, 0x5b, 0x4c, 0x67, 0x21,
  0x64, 0x0c, 0x5c, 0x1c, 0xd3, 0x2d, 0x24, 0xc4,
  0xf8, 0xad, 0x31, 0x02, 0xc5, 0xb0, 0x45, 0xe8,
  0x60, 0xd2, 0x50, 0xf4, 0xd1, 0xd6, 0x2b, 0x85,
  0x53, 0xac, 0x73, 0x96, 0x98, 0xf9, 0x1b, 0x5e,
  0xb8, 0x0f, 0xa1, 0xd3, 0xba, 0x6e, 0x43, 0x92,
  0x31, 0x69, 0x82, 0x14, 0x4a, 0xff, 0x36, 0x44,
  0x58, 0xf6, 0x41, 0xe3, 0x46, 0x85, 0x83, 0x05,
  0x96, 0x87, 0x7c, 0x0c, 0x0b, 0x70, 0x24, 0x8e,
  0x42, 0xb0, 0xd5, 0x9e, 0x7f, 0xcb, 0x26, 0xe8
};
unsigned int sigrl_dat_len = 408;
// Simulates retrieving the SIGRL for upon the SP request.
//
// @param gid Group ID for the EPID key.
// @param p_sig_rl_size Pointer to the output value of the full
//                      SIGRL size in bytes. (including the
//                      signature).
// @param p_sig_rl Pointer to the output of the SIGRL.
//
// @return int

int ias_get_sigrl(
    const sample_epid_group_id_t gid,
    uint32_t *p_sig_rl_size,
    uint8_t **p_sig_rl)
{
    int ret = 0;

    UNUSED(gid);

    do {

        if (NULL == p_sig_rl || NULL == p_sig_rl_size) {
            ret = -1;
            break;
        }
        *p_sig_rl_size = 0;//sigrl_dat_len;
        *p_sig_rl = NULL;//sigrl_dat;
        // we should try to get sig_rl from an attestation server
        break;
    }while (0);

    return(ret);
}


// Used to simulate the enrollment function of an attestation server.  It only
// gives back the SPID right now. In production, the enrollment
// occurs out of context from an attestation attempt and only
// occurs once.
//
//
// @param sp_credentials
// @param p_spid
// @param p_authentication_token
//
// @return int

int ias_enroll(
    int sp_credentials,
    sample_spid_t *p_spid,
    int *p_authentication_token)
{
    UNUSED(sp_credentials);
    UNUSED(p_authentication_token);

    if (NULL != p_spid) {
        if(memcpy_s(p_spid, sizeof(sample_spid_t), &g_sim_spid, sizeof(sample_spid_t))) {
            return(1);
        }
    } else {
        return(1);
    }
    return(0);
}
